# Generated by Django 3.0.2 on 2020-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelID', models.CharField(max_length=20)),
                ('Prefectures', models.CharField(max_length=20)),
                ('Cities', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('hotel', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=20)),
                ('companion', models.CharField(max_length=20)),
            ],
        ),
    ]
